INSERT INTO immobilie (bezeichnung, typ, baujahr, flaeche, strasse, hausnummer, plz, stadt, land)
VALUES
    ('Parkresidenz Süd', 'Mehrfamilienhaus', 1998, 850,
     'Parkstraße',
     '43',
     '33605',
     'Bielefeld',
     'Deutschland'),
    ('Altbau Ensemble Mitte', 'Wohngebaeude', 1965, 850,
     'Apfelstraße',
     '1',
     '33602',
     'Bielefeld',
     'Deutschland'),
    ('Seeblick Quartier', 'Gewerbeimmobilie', 2012, 850,
     'Seestraße',
     '21',
     '33613',
     'Bielefeld',
     'Deutschland');